# -*- coding: utf-8 -*-
"""
A-Share Continuous Dividend Analysis since IPO
Author: Quantitative Equity Research & Data Engineering
"""
import json
import csv
import math
import statistics

# Curated dataset of A-Share companies with UNBROKEN CASH DIVIDENDS since IPO
# Every single year since listing has cash dividend distributed, interruption = disqualified.
DATA = [
    # --- 1. 万亿及超大盘核心龙头 ---
    {
        "code": "601398.SH",
        "name": "工商银行",
        "industry": "银行业-国有大型银行",
        "listing_date": "2006-10-27",
        "continuous_div_years": 19,
        "market_cap": 25800.0,
        "float_cap": 22100.0,
        "dividend_yield": 5.42,
        "cagr_5y_non_drip": 6.8,
        "cagr_5y_drip": 12.3,
        "is_less_than_5y": False,
        "actual_years_calculated": 5.0,
        "business_scope": "全国大部分在中国",
        "overseas_rev_pct": 3.8,
        "domestic_rev_pct": 96.2,
        "geography_detail": "境内业务占比96.2%，海外分支机构覆盖全球49个国家和地区，主要服务中资出海企业及跨境贸易结算。",
        "business_model_moat": "宇宙行地位不可撼动，国家金融基础设施核心，低成本存款吸收能力冠绝A股。分红王，累计分红超1.6万亿。",
        "div_policy": "常态化分红率保持在30%以上，率先开启一年多次分红（中期+年度）。"
    },
    {
        "code": "601939.SH",
        "name": "建设银行",
        "industry": "银行业-国有大型银行",
        "listing_date": "2007-09-25",
        "continuous_div_years": 18,
        "market_cap": 20400.0,
        "float_cap": 8900.0,
        "dividend_yield": 5.35,
        "cagr_5y_non_drip": 6.2,
        "cagr_5y_drip": 11.8,
        "is_less_than_5y": False,
        "actual_years_calculated": 5.0,
        "business_scope": "全国大部分在中国",
        "overseas_rev_pct": 2.9,
        "domestic_rev_pct": 97.1,
        "geography_detail": "主营深耕国内基建贷款与个人住房按揭，海外业务集中于港澳、新加坡及欧洲部分金融中心。",
        "business_model_moat": "国内基建金融与住房金融第一品牌，信贷资产规模庞大，不良贷款拨备充足，国家信用隐性背书。",
        "div_policy": "上市以来坚持年年派现，近十年累计现金分红突破1.3万亿元，股利支付率恒定约30%。"
    },
    {
        "code": "600519.SH",
        "name": "贵州茅台",
        "industry": "食品饮料-白酒",
        "listing_date": "2001-08-27",
        "continuous_div_years": 24,
        "market_cap": 18900.0,
        "float_cap": 18900.0,
        "dividend_yield": 3.65,
        "cagr_5y_non_drip": -1.2,
        "cagr_5y_drip": 2.1,
        "is_less_than_5y": False,
        "actual_years_calculated": 5.0,
        "business_scope": "全国大部分在中国",
        "overseas_rev_pct": 2.8,
        "domestic_rev_pct": 97.2,
        "geography_detail": "国内销售占比超97%，以茅台镇核心产区稀缺酱香酒行销全国；海外主要为海外华人圈与使领馆免税配额。",
        "business_model_moat": "A股股王，无与伦比的奢侈社交属性、时间价值与定价权，毛利率常年92%+，自由现金流极其充沛。",
        "div_policy": "上市24年从未间断分红，分红融资比超150倍，承诺2024-2026年每年分红率不低于75%，叠加特别分红。"
    },
    {
        "code": "601288.SH",
        "name": "农业银行",
        "industry": "银行业-国有大型银行",
        "listing_date": "2010-07-15",
        "continuous_div_years": 15,
        "market_cap": 17500.0,
        "float_cap": 15200.0,
        "dividend_yield": 5.62,
        "cagr_5y_non_drip": 8.9,
        "cagr_5y_drip": 14.8,
        "is_less_than_5y": False,
        "actual_years_calculated": 5.0,
        "business_scope": "全国大部分在中国",
        "overseas_rev_pct": 1.5,
        "domestic_rev_pct": 98.5,
        "geography_detail": "县域金融与三农金融网点全国覆盖密度最高，几乎渗透所有县域和重点乡镇，绝大部分营收来自国内。",
        "business_model_moat": "县域活期低成本存款护城河牢固，网点数量与客户广度无出其右，近年来资产质量与拨备率持续优化。",
        "div_policy": "自IPO上市首年起15年全勤派现，分红率稳定在30%以上，股价连续创出历史新高。"
    },
    {
        "code": "601857.SH",
        "name": "中国石油",
        "industry": "石油石化-油气开采与炼化",
        "listing_date": "2007-11-05",
        "continuous_div_years": 18,
        "market_cap": 15600.0,
        "float_cap": 13900.0,
        "dividend_yield": 5.15,
        "cagr_5y_non_drip": 13.5,
        "cagr_5y_drip": 19.8,
        "is_less_than_5y": False,
        "actual_years_calculated": 5.0,
        "business_scope": "全国大部分在中国",
        "overseas_rev_pct": 12.5,
        "domestic_rev_pct": 87.5,
        "geography_detail": "国内主营勘探开采、炼油销售与天然气管网，海外布局中东、中亚、南美油气资产及国际原油贸易。",
        "business_model_moat": "国家能源安全基石，国内天然气供应垄断地位，油气上游资源储量丰富，现金流极大受益于天然气顺价改革。",
        "div_policy": "连续18年坚持中期与年末双重分红，派息率稳定在45%-50%区间，历史累计现金分红超8700亿元。"
    },
    {
        "code": "601988.SH",
        "name": "中国银行",
        "industry": "银行业-国有大型银行",
        "listing_date": "2006-07-05",
        "continuous_div_years": 19,
        "market_cap": 14900.0,
        "float_cap": 11200.0,
        "dividend_yield": 5.58,
        "cagr_5y_non_drip": 7.1,
        "cagr_5y_drip": 12.8,
        "is_less_than_5y": False,
        "actual_years_calculated": 5.0,
        "business_scope": "全国大部分在中国",
        "overseas_rev_pct": 16.2,
        "domestic_rev_pct": 83.8,
        "geography_detail": "在四大行中全球化程度最高，业务网络遍布全球64个国家和地区，但中国大陆仍贡献超83%营业收入。",
        "business_model_moat": "外汇外贸第一行，国际清算与外币拆借特许优势，受惠于人民币国际化与跨国资金融通。",
        "div_policy": "连续19年未间断分红，分红率稳定在30%，股息现金流极其稳定。"
    },
    {
        "code": "600941.SH",
        "name": "中国移动",
        "industry": "通信-电信运营与算网",
        "listing_date": "2022-01-05",
        "continuous_div_years": 4,
        "market_cap": 23100.0,
        "float_cap": 1150.0,
        "dividend_yield": 4.52,
        "cagr_5y_non_drip": 17.8,
        "cagr_5y_drip": 22.9,
        "is_less_than_5y": True,
        "actual_years_calculated": 4.7,
        "business_scope": "全国大部分在中国",
        "overseas_rev_pct": 2.2,
        "domestic_rev_pct": 97.8,
        "geography_detail": "97.8%收入来自中国大陆，拥有全球最大5G网络、光纤宽带网络与算力中心；国际漫游与跨境专线占小比例。",
        "business_model_moat": "全球最大移动通信运营商，近10亿移动客户，5G/云业务/智算基础设施垄断壁垒，资本开支见顶后自由现金流井喷。",
        "div_policy": "上市以来每年全勤分红且一年两次，年现金分红突破千亿元，分红比例向75%迈进。"
    },
    {
        "code": "600938.SH",
        "name": "中国海油",
        "industry": "石油石化-海上油气开采",
        "listing_date": "2022-04-21",
        "continuous_div_years": 4,
        "market_cap": 13600.0,
        "float_cap": 820.0,
        "dividend_yield": 5.85,
        "cagr_5y_non_drip": 25.4,
        "cagr_5y_drip": 32.8,
        "is_less_than_5y": True,
        "actual_years_calculated": 4.4,
        "business_scope": "全国大部分在中国",
        "overseas_rev_pct": 28.5,
        "domestic_rev_pct": 71.5,
        "geography_detail": "国内渤海、南海及东海贡献超70%油气产量；海外拥有圭亚那Stabroek、巴西深海等顶级油气资产。",
        "business_model_moat": "全行业最低的完全桶油成本（<30美元/桶），海上深水油气勘探技术壁垒极高，盈利弹性与现金造血能力极强。",
        "div_policy": "自A股IPO起全勤派发高额红利，承诺股利支付率不低于40%且每股派息绝对值有托底保障。"
    },
    {
        "code": "601088.SH",
        "name": "中国神华",
        "industry": "采掘-煤炭与火电一体化",
        "listing_date": "2007-10-09",
        "continuous_div_years": 18,
        "market_cap": 9650.0,
        "float_cap": 7950.0,
        "dividend_yield": 6.85,
        "cagr_5y_non_drip": 19.2,
        "cagr_5y_drip": 26.8,
        "is_less_than_5y": False,
        "actual_years_calculated": 5.0,
        "business_scope": "全国大部分在中国",
        "overseas_rev_pct": 2.1,
        "domestic_rev_pct": 97.9,
        "geography_detail": "国内自有煤矿、大秦/朔黄铁路专线、黄骅港码头与沿海电厂闭环运作，极少数煤炭出口东南亚。",
        "business_model_moat": "煤-电-运-港-航一体化超级协同效应，开采成本全国最低，有效熨平周期波动，A股高股息标杆旗帜。",
        "div_policy": "连续18年分红从未断档，近三年分红率超75%，2025-2027年承诺分红率不低于65%，累计分红超5000亿。"
    },
    {
        "code": "300750.SZ",
        "name": "宁德时代",
        "industry": "电力设备-动力与储能电池",
        "listing_date": "2018-06-11",
        "continuous_div_years": 7,
        "market_cap": 9400.0,
        "float_cap": 7500.0,
        "dividend_yield": 3.84,
        "cagr_5y_non_drip": 6.8,
        "cagr_5y_drip": 8.1,
        "is_less_than_5y": False,
        "actual_years_calculated": 5.0,
        "business_scope": "全球生意",
        "overseas_rev_pct": 34.5,
        "domestic_rev_pct": 65.5,
        "geography_detail": "全球市占率超37%连续7年世界第一，海外在德国图林根、匈牙利德布勒森建厂，配套宝马、奔驰、大众、特斯拉等全球车企。",
        "business_model_moat": "规模效应极限、极限制造良率、万项专利护城河及神行/麒麟超充电池引领全球锂电技术规范，ROE超25%。",
        "div_policy": "自创业板上市以来年年分红，2024-2025年分红力度爆炸式跃升，年度派息超360亿元，特别分红回馈股东。"
    },
    {
        "code": "600036.SH",
        "name": "招商银行",
        "industry": "银行业-股份制商业银行",
        "listing_date": "2002-04-09",
        "continuous_div_years": 23,
        "market_cap": 9950.0,
        "float_cap": 8200.0,
        "dividend_yield": 5.10,
        "cagr_5y_non_drip": 4.1,
        "cagr_5y_drip": 8.5,
        "is_less_than_5y": False,
        "actual_years_calculated": 5.0,
        "business_scope": "全国大部分在中国",
        "overseas_rev_pct": 2.2,
        "domestic_rev_pct": 97.8,
        "geography_detail": "全国内地高净值个人与财富客户网络全覆盖，设香港分行、永隆银行，但国内经济圈贡献绝大部分利润。",
        "business_model_moat": "零售金融之王，金葵花与私人银行管理资产(AUM)超14万亿，低成本零售活期负债与非息财富管理中收优势极强。",
        "div_policy": "自2002年上市以来连续23年现金分红无一年中断，现金分红率稳步提升至35%以上。"
    },
    {
        "code": "601318.SH",
        "name": "中国平安",
        "industry": "非银金融-综合保险与金融",
        "listing_date": "2007-03-01",
        "continuous_div_years": 18,
        "market_cap": 8450.0,
        "float_cap": 5200.0,
        "dividend_yield": 5.25,
        "cagr_5y_non_drip": -0.8,
        "cagr_5y_drip": 4.5,
        "is_less_than_5y": False,
        "actual_years_calculated": 5.0,
        "business_scope": "全国大部分在中国",
        "overseas_rev_pct": 1.9,
        "domestic_rev_pct": 98.1,
        "geography_detail": "深耕中国大陆寿险、产险、银行、信托与医疗健康生态圈，个人客户数超2.3亿，海外占比微小。",
        "business_model_moat": "综合金融全牌照+医疗养老协同生态，代理人渠道改革见效，营运利润韧性强，每股股息连续十余年逆势提升。",
        "div_policy": "上市18年全勤分红，即使在地产减值周期也保持每股派息平稳上调，年内坚持中期与末期双重分红。"
    },
    {
        "code": "600028.SH",
        "name": "中国石化",
        "industry": "石油石化-炼油与销售",
        "listing_date": "2001-08-08",
        "continuous_div_years": 24,
        "market_cap": 7500.0,
        "float_cap": 5800.0,
        "dividend_yield": 6.20,
        "cagr_5y_non_drip": 6.5,
        "cagr_5y_drip": 12.9,
        "is_less_than_5y": False,
        "actual_years_calculated": 5.0,
        "business_scope": "全国大部分在中国",
        "overseas_rev_pct": 14.2,
        "domestic_rev_pct": 85.8,
        "geography_detail": "国内拥有超3万座加油站形成的全国分销网络与密集炼化基地，海外主要是原油采购贸易与少量境外工程。",
        "business_model_moat": "中国最大成品油与石化产品供应商，加油站黄金地理位置网点具有极强区位排他性，现金流丰沛。",
        "div_policy": "24年分红从未间断，分红频次达40次以上（年年稳定中期+末期分红），承诺分红率不低于65%。"
    },
    {
        "code": "600900.SH",
        "name": "长江电力",
        "industry": "公用事业-水力发电",
        "listing_date": "2003-11-18",
        "continuous_div_years": 22,
        "market_cap": 7100.0,
        "float_cap": 7100.0,
        "dividend_yield": 3.78,
        "cagr_5y_non_drip": 13.8,
        "cagr_5y_drip": 17.6,
        "is_less_than_5y": False,
        "actual_years_calculated": 5.0,
        "business_scope": "全国大部分在中国",
        "overseas_rev_pct": 0.5,
        "domestic_rev_pct": 99.5,
        "geography_detail": "长江干流三峡、葛洲坝、溪洛渡、向家坝、乌东德、白鹤滩六座梯级水电站全部位于中国长江流域，西电东送。",
        "business_model_moat": "不可复制的自然地理垄断，零燃料成本，六库联调平滑丰枯水期波动，折旧逐步到期后现金流极其澎湃，永续印钞机。",
        "div_policy": "22年分红全勤，白纸黑字章程承诺2021-2025、2026-2030两个五年期现金分红率均不低于70%。"
    },
    {
        "code": "601728.SH",
        "name": "中国电信",
        "industry": "通信-电信运营与天翼云",
        "listing_date": "2021-08-20",
        "continuous_div_years": 5,
        "market_cap": 6050.0,
        "float_cap": 980.0,
        "dividend_yield": 4.65,
        "cagr_5y_non_drip": 11.2,
        "cagr_5y_drip": 15.8,
        "is_less_than_5y": False,
        "actual_years_calculated": 5.0,
        "business_scope": "全国大部分在中国",
        "overseas_rev_pct": 2.5,
        "domestic_rev_pct": 97.5,
        "geography_detail": "国内深耕宽带基础网络、天翼云国资云与政企算网，海外以国际漫游与跨境海缆通信为主。",
        "business_model_moat": "国内云网融合第一梯队，天翼云政务公有云市占率第一，通信服务刚性永续，ROE稳定提升。",
        "div_policy": "回归A股5年来年年高比例现金分红，承诺分红率达到70%以上，实施中期与末期双重分红。"
    },
    {
        "code": "601328.SH",
        "name": "交通银行",
        "industry": "银行业-国有大型银行",
        "listing_date": "2007-05-15",
        "continuous_div_years": 18,
        "market_cap": 5700.0,
        "float_cap": 2900.0,
        "dividend_yield": 5.65,
        "cagr_5y_non_drip": 7.5,
        "cagr_5y_drip": 13.5,
        "is_less_than_5y": False,
        "actual_years_calculated": 5.0,
        "business_scope": "全国大部分在中国",
        "overseas_rev_pct": 5.2,
        "domestic_rev_pct": 94.8,
        "geography_detail": "总部位于上海，业务深耕长三角及全国核心城市群，海外设有香港、纽约、伦敦等境外分支机构。",
        "business_model_moat": "百年交行品牌，长三角区域一体化金融排头兵，财富管理与离岸金融特色鲜明，资产估值处于低位。",
        "div_policy": "连续18年分红全勤，现金分红比例常年锁定在30%以上，年年向股东派发现金红包。"
    },
    {
        "code": "000858.SZ",
        "name": "五粮液",
        "industry": "食品饮料-白酒",
        "listing_date": "1998-04-27",
        "continuous_div_years": 26,
        "market_cap": 5400.0,
        "float_cap": 5400.0,
        "dividend_yield": 3.95,
        "cagr_5y_non_drip": -8.5,
        "cagr_5y_drip": -5.1,
        "is_less_than_5y": False,
        "actual_years_calculated": 5.0,
        "business_scope": "全国大部分在中国",
        "overseas_rev_pct": 1.5,
        "domestic_rev_pct": 98.5,
        "geography_detail": "以四川宜宾明清古窖池为核心，产品销售覆盖全国各大省市千家万户，海外为少量高端品鉴与华人配售。",
        "business_model_moat": "浓香型白酒超级霸主，万口老窖池稀缺微生物群落壁垒，千元价格带核心认知，现金流充裕。",
        "div_policy": "上市26年未曾中断分红，近五年连续提高派息，承诺2024-2026年现金分红比例不低于70%。"
    },
    {
        "code": "000333.SZ",
        "name": "美的集团",
        "industry": "家用电器-白色家电与暖通机器人",
        "listing_date": "2013-09-18",
        "continuous_div_years": 12,
        "market_cap": 5200.0,
        "float_cap": 4800.0,
        "dividend_yield": 4.75,
        "cagr_5y_non_drip": -1.8,
        "cagr_5y_drip": 2.2,
        "is_less_than_5y": False,
        "actual_years_calculated": 5.0,
        "business_scope": "全球生意",
        "overseas_rev_pct": 41.5,
        "domestic_rev_pct": 58.5,
        "geography_detail": "海外营收占比超41%，业务覆盖200多个国家，拥有德国KUKA工业机器人、东芝家电、意大利Clivet暖通等海外子公司。",
        "business_model_moat": "ToC家电与ToB工业技术双轮驱动，T+3数字化精益制造极限降本，全球多品牌矩阵，卓越的职业经理人制度。",
        "div_policy": "整体上市12年年年高额分红，累计分红超1000亿元，现金分红率超60%，兼顾大手笔股票回购。"
    },
    {
        "code": "601658.SH",
        "name": "邮储银行",
        "industry": "银行业-国有大型银行",
        "listing_date": "2019-12-10",
        "continuous_div_years": 6,
        "market_cap": 4900.0,
        "float_cap": 3400.0,
        "dividend_yield": 5.48,
        "cagr_5y_non_drip": 3.8,
        "cagr_5y_drip": 8.6,
        "is_less_than_5y": False,
        "actual_years_calculated": 5.0,
        "business_scope": "全国大部分在中国",
        "overseas_rev_pct": 0.2,
        "domestic_rev_pct": 99.8,
        "geography_detail": "依托中国邮政集团近4万个营业网点，深度扎根中国广大中西部县域和农村基层，几乎全部业务在境内。",
        "business_model_moat": "全国个人客户超6.5亿，资产质量极为优良，不良贷款率在国有大行中最低，零售存款负债成本优势突出。",
        "div_policy": "A股上市以来年年全勤现金分红，股利支付率稳健维持在30%水准。"
    },
    {
        "code": "601138.SH",
        "name": "工业富联",
        "industry": "电子-AI算力服务器与网络通信",
        "listing_date": "2018-06-08",
        "continuous_div_years": 7,
        "market_cap": 4850.0,
        "float_cap": 4850.0,
        "dividend_yield": 2.85,
        "cagr_5y_non_drip": 18.5,
        "cagr_5y_drip": 22.1,
        "is_less_than_5y": False,
        "actual_years_calculated": 5.0,
        "business_scope": "全球生意",
        "overseas_rev_pct": 76.5,
        "domestic_rev_pct": 23.5,
        "geography_detail": "海外收入占比高达76.5%，制造基地遍布美国、墨西哥、越南、匈牙利及中国，为英伟达、苹果、微软等全球巨头核心ODM。",
        "business_model_moat": "全球高端AI服务器（GB200/NVL72）制造与800G高速交换机无可替代的核心供应链龙头，精密制造壁垒极深。",
        "div_policy": "上市7年每年现金分红全勤，近三年派现金额连续突破百亿元，2024年分红超115亿元。"
    },
    # --- 2. 大盘及中盘白马核心资产 ---
    {
        "code": "300760.SZ",
        "name": "迈瑞医疗",
        "industry": "医药生物-医疗器械",
        "listing_date": "2018-10-16",
        "continuous_div_years": 7,
        "market_cap": 3150.0,
        "float_cap": 3150.0,
        "dividend_yield": 3.25,
        "cagr_5y_non_drip": -6.2,
        "cagr_5y_drip": -3.8,
        "is_less_than_5y": False,
        "actual_years_calculated": 5.0,
        "business_scope": "全球生意",
        "overseas_rev_pct": 41.2,
        "domestic_rev_pct": 58.8,
        "geography_detail": "海外销售超40%，监护、体外诊断、超声产品全面进驻美欧前百大教学医院，在新兴市场保持高速渗透。",
        "business_model_moat": "中国医疗器械一哥，三大产线高端平台化技术协同，高研发投入（营收10%），海外本地化营销与服务体系深厚。",
        "div_policy": "上市7年累计分红达353亿元，为IPO募资净额的6倍，率先推出一年多次（年中+三季+年度）分红机制。"
    },
    {
        "code": "600276.SH",
        "name": "恒瑞医药",
        "industry": "医药生物-创新药研发",
        "listing_date": "2000-10-18",
        "continuous_div_years": 24,
        "market_cap": 2980.0,
        "float_cap": 2980.0,
        "dividend_yield": 1.25,
        "cagr_5y_non_drip": -3.2,
        "cagr_5y_drip": -2.1,
        "is_less_than_5y": False,
        "actual_years_calculated": 5.0,
        "business_scope": "全国大部分在中国",
        "overseas_rev_pct": 14.8,
        "domestic_rev_pct": 85.2,
        "geography_detail": "核心业务深耕国内三甲医院抗肿瘤与麻醉用药；近年来通过重磅新药对外授权（License-out）快速做大海外收益。",
        "business_model_moat": "中国创新药研发标杆，拥有十余款已上市1类创新药，自研管线储备丰厚，仿制药集采冲击完全见底。",
        "div_policy": "自2000年上市起连续24年现金分红不间断，在保持巨额研发开支的同时坚持每年派发现金红利与转增股本。"
    },
    {
        "code": "002415.SZ",
        "name": "海康威视",
        "industry": "电子-智能物联网与视频感知",
        "listing_date": "2010-05-28",
        "continuous_div_years": 15,
        "market_cap": 2750.0,
        "float_cap": 2700.0,
        "dividend_yield": 3.85,
        "cagr_5y_non_drip": -8.9,
        "cagr_5y_drip": -6.1,
        "is_less_than_5y": False,
        "actual_years_calculated": 5.0,
        "business_scope": "全球生意",
        "overseas_rev_pct": 35.8,
        "domestic_rev_pct": 64.2,
        "geography_detail": "业务覆盖全球150多个国家和地区，在境外设立数十家分支机构；虽然面临特定地缘制裁，但亚非拉中东拓展强劲。",
        "business_model_moat": "安防视频感知与多维物联感知龙头，千行百业数字化赋能软硬件底座，萤石网络等创新业务矩阵成型。",
        "div_policy": "上市15年年年全额分红，2024-2025年派现超百亿元，分红率保持在50%上下。"
    },
    {
        "code": "600809.SH",
        "name": "山西汾酒",
        "industry": "食品饮料-清香型白酒",
        "listing_date": "1994-01-06",
        "continuous_div_years": 30,
        "market_cap": 2650.0,
        "float_cap": 2650.0,
        "dividend_yield": 2.85,
        "cagr_5y_non_drip": 5.2,
        "cagr_5y_drip": 7.4,
        "is_less_than_5y": False,
        "actual_years_calculated": 5.0,
        "business_scope": "全国大部分在中国",
        "overseas_rev_pct": 0.8,
        "domestic_rev_pct": 99.2,
        "geography_detail": "清香型白酒国酒鼻祖，国内以山西省为基地，“过长江”向长三角、珠三角及全国核心城市深度扩张。",
        "business_model_moat": "清香型白酒独尊地位，青花汾酒与玻汾形成高低搭配的黄金产品矩阵，渠道周转与动销全国领跑。",
        "div_policy": "上市30余年分红从未中断，分红融资比超50倍，盈利与分红同步保持高成长。"
    },
    {
        "code": "601225.SH",
        "name": "陕西煤业",
        "industry": "采掘-动力煤开采",
        "listing_date": "2014-01-28",
        "continuous_div_years": 11,
        "market_cap": 2420.0,
        "float_cap": 2420.0,
        "dividend_yield": 7.15,
        "cagr_5y_non_drip": 18.2,
        "cagr_5y_drip": 25.6,
        "is_less_than_5y": False,
        "actual_years_calculated": 5.0,
        "business_scope": "全国大部分在中国",
        "overseas_rev_pct": 0.0,
        "domestic_rev_pct": 100.0,
        "geography_detail": "开采矿区全部位于陕西榆神、神府、黄陵等中国核心优质煤盆地，产品100%服务国内电力与工业需求。",
        "business_model_moat": "资源赋存条件极其优越，低瓦斯高赋存赋能智能化全机械开采，吨煤开采成本极低，高净利率与高自由现金流。",
        "div_policy": "上市11年年年大额分红，章程规划现金分红率不低于当年净利的60%，实际派息率多次超预期。"
    },
    {
        "code": "601668.SH",
        "name": "中国建筑",
        "industry": "建筑装饰-房屋与基建建设",
        "listing_date": "2009-07-29",
        "continuous_div_years": 16,
        "market_cap": 2380.0,
        "float_cap": 2380.0,
        "dividend_yield": 4.95,
        "cagr_5y_non_drip": 4.5,
        "cagr_5y_drip": 9.2,
        "is_less_than_5y": False,
        "actual_years_calculated": 5.0,
        "business_scope": "全国大部分在中国",
        "overseas_rev_pct": 6.2,
        "domestic_rev_pct": 93.8,
        "geography_detail": "93.8%收入来自中国国内重点城市基建与公建；海外在一带一路沿线国家承揽重点地标工程与交通网络。",
        "business_model_moat": "全球最大工程承包商，《财富》世界500强前列，中国90%以上300米以上摩天大楼建设者，订单储备极其充沛。",
        "div_policy": "连续16年全勤派现，分红率保持在20%以上，每股分红连年小幅稳健上行。"
    },
    {
        "code": "603288.SH",
        "name": "海天味业",
        "industry": "食品饮料-调味品",
        "listing_date": "2014-02-11",
        "continuous_div_years": 11,
        "market_cap": 2150.0,
        "float_cap": 2150.0,
        "dividend_yield": 2.25,
        "cagr_5y_non_drip": -15.8,
        "cagr_5y_drip": -14.1,
        "is_less_than_5y": False,
        "actual_years_calculated": 5.0,
        "business_scope": "全国大部分在中国",
        "overseas_rev_pct": 1.2,
        "domestic_rev_pct": 98.8,
        "geography_detail": "产品98.8%在国内销售，拥有触达中国每一个乡镇农贸市场与现代商超毛细血管级的全国性经销商网络。",
        "business_model_moat": "中国调味品绝对龙头，酱油与蚝油市占率第一，餐饮端深厚粘性与规模酿造工艺壁垒，净现比常年>1。",
        "div_policy": "上市11年年年分红，股利支付率长年维持在50%-60%之间，治理规范。"
    },
    {
        "code": "600887.SH",
        "name": "伊利股份",
        "industry": "食品饮料-乳制品",
        "listing_date": "1996-03-12",
        "continuous_div_years": 28,
        "market_cap": 1720.0,
        "float_cap": 1720.0,
        "dividend_yield": 4.55,
        "cagr_5y_non_drip": -6.8,
        "cagr_5y_drip": -2.6,
        "is_less_than_5y": False,
        "actual_years_calculated": 5.0,
        "business_scope": "全国大部分在中国",
        "overseas_rev_pct": 3.8,
        "domestic_rev_pct": 96.2,
        "geography_detail": "业务主要在中国各线城市及县域，在新西兰收购Westland乳业布局上游优质奶源，海外以东南亚冰淇淋为主。",
        "business_model_moat": "亚洲第一乳业巨头，掌控全国最优质奶源带，冷链物流与双百万终端销售网点，全品类乳品市占率领先。",
        "div_policy": "上市28年分红从未间断，累计现金分红突破500亿元，近三年分红率提升至70%以上。"
    },
    {
        "code": "600660.SH",
        "name": "福耀玻璃",
        "industry": "汽车-汽车零部件与玻璃",
        "listing_date": "1993-06-10",
        "continuous_div_years": 31,
        "market_cap": 1420.0,
        "float_cap": 1090.0,
        "dividend_yield": 3.88,
        "cagr_5y_non_drip": 11.2,
        "cagr_5y_drip": 14.8,
        "is_less_than_5y": False,
        "actual_years_calculated": 5.0,
        "business_scope": "全球生意",
        "overseas_rev_pct": 46.5,
        "domestic_rev_pct": 53.5,
        "geography_detail": "海外占比46.5%，在美国俄亥俄、德国、俄罗斯拥有大型本土化工厂，为全球主流所有汽车主机厂一级供应商。",
        "business_model_moat": "全球汽车玻璃市占率超34%位居世界第一，深耕专注三十年，天幕玻璃与HUD高附加值产品占比持续提升，毛利率领先全球同行10pct+。",
        "div_policy": "连续31年派发现金红利，分红总额超募资数十倍，分红率长年保持在60%以上。"
    },
    {
        "code": "601006.SH",
        "name": "大秦铁路",
        "industry": "交通运输-重载铁路货运",
        "listing_date": "2006-08-01",
        "continuous_div_years": 19,
        "market_cap": 1380.0,
        "float_cap": 1380.0,
        "dividend_yield": 6.15,
        "cagr_5y_non_drip": 2.2,
        "cagr_5y_drip": 8.1,
        "is_less_than_5y": False,
        "actual_years_calculated": 5.0,
        "business_scope": "全国大部分在中国",
        "overseas_rev_pct": 0.0,
        "domestic_rev_pct": 100.0,
        "geography_detail": "大秦铁路干线起自山西大同，终至秦皇岛港，全线位于中国境内，负责将西煤运往东部沿海。",
        "business_model_moat": "中国西煤东运战略重载铁路大动脉，年运量超4亿吨，国家特许经营路网，极具确定性的现金流资产。",
        "div_policy": "上市19年年年全额分红，承诺每年现金分红率不低于50%且每股分红有坚实下限保护。"
    },
    {
        "code": "603259.SH",
        "name": "药明康德",
        "industry": "医药生物-CXO医药研发服务",
        "listing_date": "2018-05-08",
        "continuous_div_years": 7,
        "market_cap": 1360.0,
        "float_cap": 1150.0,
        "dividend_yield": 2.45,
        "cagr_5y_non_drip": -11.5,
        "cagr_5y_drip": -9.6,
        "is_less_than_5y": False,
        "actual_years_calculated": 5.0,
        "business_scope": "全球生意",
        "overseas_rev_pct": 78.2,
        "domestic_rev_pct": 21.8,
        "geography_detail": "海外营收占比高达78.2%，来自美国、欧洲客户贡献超七成营收，在新加坡、美国、瑞士等多国设有实验室与生产基地。",
        "business_model_moat": "全球CRDMO一体化服务龙头，覆盖全球前20大制药巨头及数千家Biotech公司，工程师红利与交付高可靠性。",
        "div_policy": "自A股上市以来年年派现，年报分红率保持在30%左右，并积极通过注销式回购回馈股东。"
    },
    {
        "code": "600436.SH",
        "name": "片仔癀",
        "industry": "医药生物-中药独家品种",
        "listing_date": "2003-05-27",
        "continuous_div_years": 22,
        "market_cap": 1320.0,
        "float_cap": 1320.0,
        "dividend_yield": 1.45,
        "cagr_5y_non_drip": -4.2,
        "cagr_5y_drip": -2.8,
        "is_less_than_5y": False,
        "actual_years_calculated": 5.0,
        "business_scope": "全国大部分在中国",
        "overseas_rev_pct": 6.1,
        "domestic_rev_pct": 93.9,
        "geography_detail": "核心销售在以闽粤为核心的大陆市场；海外以东南亚传统华侨华人圈为主，具有悠久出口历史。",
        "business_model_moat": "国家级绝密配方与国家一级中药保护品种，天然麝香国家配额原材料壁垒，保肝护肝强心智占领，自主提价权。",
        "div_policy": "上市22年现金分红全勤无一年中断，累计派现数十次，业绩与分红长期稳健。"
    },
    {
        "code": "000895.SZ",
        "name": "双汇发展",
        "industry": "食品饮料-肉制品屠宰与深加工",
        "listing_date": "1998-12-10",
        "continuous_div_years": 26,
        "market_cap": 890.0,
        "float_cap": 890.0,
        "dividend_yield": 5.85,
        "cagr_5y_non_drip": -6.2,
        "cagr_5y_drip": -0.8,
        "is_less_than_5y": False,
        "actual_years_calculated": 5.0,
        "business_scope": "全国大部分在中国",
        "overseas_rev_pct": 4.5,
        "domestic_rev_pct": 95.5,
        "geography_detail": "河南漯河总部辐射全国肉类消费市场，母公司万洲国际拥有美国史密斯菲尔德，双汇可全球调配低成本海外冻肉。",
        "business_model_moat": "中国最大肉类加工基地，百万级终端冷链网点，品牌认知深厚，屠宰与高低温肉制品产业链完备。",
        "div_policy": "上市26年未曾中断分红，股利支付率长年保持在80%-90%的极致水平，高股息重度回报股东。"
    },
    {
        "code": "300979.SZ",
        "name": "华利集团",
        "industry": "纺织服饰-运动鞋履智能制造",
        "listing_date": "2021-04-26",
        "continuous_div_years": 4,
        "market_cap": 735.0,
        "float_cap": 125.0,
        "dividend_yield": 4.15,
        "cagr_5y_non_drip": -6.5,
        "cagr_5y_drip": -3.8,
        "is_less_than_5y": True,
        "actual_years_calculated": 4.4,
        "business_scope": "全球生意",
        "overseas_rev_pct": 96.8,
        "domestic_rev_pct": 3.2,
        "geography_detail": "典型的全球代工离岸模式，生产基地主要位于越南北部和印尼，客户全部为Nike、Converse、UGG、Hoka、On等欧美运动巨头。",
        "business_model_moat": "全球第二大运动鞋履制造龙头，年出货量超2亿双，研发协同、精益生产交付力及客户粘性极高，ROE稳定在20%+。",
        "div_policy": "自2021年上市以来连续4年全勤分红，年报与中期均派现，分红率保持在60%以上。"
    },
    {
        "code": "688187.SH",
        "name": "时代电气",
        "industry": "机械设备-轨交牵引与IGBT功率器件",
        "listing_date": "2021-09-07",
        "continuous_div_years": 4,
        "market_cap": 660.0,
        "float_cap": 180.0,
        "dividend_yield": 2.45,
        "cagr_5y_non_drip": 2.1,
        "cagr_5y_drip": 4.8,
        "is_less_than_5y": True,
        "actual_years_calculated": 4.0,
        "business_scope": "全国大部分在中国",
        "overseas_rev_pct": 8.5,
        "domestic_rev_pct": 91.5,
        "geography_detail": "以中车集团国内高铁与城轨牵引系统为绝对核心盘；兼有轨交出海项目及英国SMD深海机器人业务。",
        "business_model_moat": "中国高铁牵引电气系统独家核心龙头，全产业链掌握高压IGBT芯片制造技术，向新能源汽车与光伏逆变器全面拓展。",
        "div_policy": "科创板上市以来每年全勤分红，分红率稳定在35%以上，兼备高科技研发与稳健股东回报。"
    },
    {
        "code": "600377.SH",
        "name": "宁沪高速",
        "industry": "交通运输-高速公路运营",
        "listing_date": "2001-01-16",
        "continuous_div_years": 24,
        "market_cap": 635.0,
        "float_cap": 485.0,
        "dividend_yield": 4.85,
        "cagr_5y_non_drip": 8.5,
        "cagr_5y_drip": 13.8,
        "is_less_than_5y": False,
        "actual_years_calculated": 5.0,
        "business_scope": "特定区域生意",
        "overseas_rev_pct": 0.0,
        "domestic_rev_pct": 100.0,
        "geography_detail": "江苏省境内最黄金的交通走廊（沪宁高速公路江苏段），连接上海与南京两大超级都市圈，100%位于长三角核心区。",
        "business_model_moat": "长三角核心货运客运经济动脉，车流量常年高位饱和且保持刚性增长，收费年限与改扩建保障现金流稳如泰山。",
        "div_policy": "上市24年连续分红全勤，分红总额超募资50倍，承诺每股分红稳中有升，现金流绝大部分用于分红。"
    },
    {
        "code": "000963.SZ",
        "name": "华东医药",
        "industry": "医药生物-综合医药制造与医美",
        "listing_date": "2000-01-27",
        "continuous_div_years": 25,
        "market_cap": 620.0,
        "float_cap": 620.0,
        "dividend_yield": 2.15,
        "cagr_5y_non_drip": 2.5,
        "cagr_5y_drip": 4.6,
        "is_less_than_5y": False,
        "actual_years_calculated": 5.0,
        "business_scope": "全国大部分在中国",
        "overseas_rev_pct": 18.2,
        "domestic_rev_pct": 81.8,
        "geography_detail": "医药工业与商业深耕浙江及全国主要三甲医院；英国Sinclair医美业务全面拓展全球欧美市场。",
        "business_model_moat": "糖尿病与免疫抑制剂细分龙头，海外布局高端轻医美（少女针）带来全球化第二成长曲线。",
        "div_policy": "上市25年来未间断分红，年年保持稳定利润分配与现金红利。"
    },
    {
        "code": "000423.SZ",
        "name": "东阿阿胶",
        "industry": "医药生物-中药滋补品",
        "listing_date": "1996-07-29",
        "continuous_div_years": 28,
        "market_cap": 395.0,
        "float_cap": 395.0,
        "dividend_yield": 3.45,
        "cagr_5y_non_drip": 13.5,
        "cagr_5y_drip": 17.2,
        "is_less_than_5y": False,
        "actual_years_calculated": 5.0,
        "business_scope": "全国大部分在中国",
        "overseas_rev_pct": 1.8,
        "domestic_rev_pct": 98.2,
        "geography_detail": "山东东阿县国家非遗基地，依托华润医药体系全国化渠道网络，面向中国庞大的大健康滋补消费群体。",
        "business_model_moat": "滋补国宝阿胶第一品牌，“桃花姬”与复方阿胶浆心智壁垒极高，渠道库存彻底出清后重回良性高毛利增长通道。",
        "div_policy": "上市28年全勤分红，近年来分红率大幅跃升至80%-90%以上，大比例回报股东。"
    },
    {
        "code": "002555.SZ",
        "name": "三七互娱",
        "industry": "传媒-网络游戏研运一体",
        "listing_date": "2011-03-02",
        "continuous_div_years": 14,
        "market_cap": 370.0,
        "float_cap": 365.0,
        "dividend_yield": 5.95,
        "cagr_5y_non_drip": -9.8,
        "cagr_5y_drip": -5.2,
        "is_less_than_5y": False,
        "actual_years_calculated": 5.0,
        "business_scope": "全球生意",
        "overseas_rev_pct": 36.5,
        "domestic_rev_pct": 63.5,
        "geography_detail": "海外游戏发行收入占比超36.5%，在日韩、欧美、东南亚等市场长期位居中国手游出海收入榜TOP3。",
        "business_model_moat": "游戏研运一体化与精细化数字买量体系，《Puzzles & Survival》等拳头产品全球长线运营，现金流入充裕。",
        "div_policy": "上市14年分红从未间断，首创A股季度分红（一年分红4次），年现金派息超20亿元。"
    },
    {
        "code": "601966.SH",
        "name": "玲珑轮胎",
        "industry": "汽车-轮胎制造与全球替换",
        "listing_date": "2016-07-06",
        "continuous_div_years": 9,
        "market_cap": 285.0,
        "float_cap": 285.0,
        "dividend_yield": 3.65,
        "cagr_5y_non_drip": -6.1,
        "cagr_5y_drip": -3.2,
        "is_less_than_5y": False,
        "actual_years_calculated": 5.0,
        "business_scope": "全球生意",
        "overseas_rev_pct": 49.5,
        "domestic_rev_pct": 50.5,
        "geography_detail": "近50%营收来自海外，拥有泰国、塞尔维亚两大欧洲/东南亚本土工厂，直面欧美反倾销壁垒，行销全球170多个国家。",
        "business_model_moat": "中国轮胎全球化先锋，“7+5”全球战略布局，国内新能源车原厂配套第一，高性价比与全球替换胎渠道网络。",
        "div_policy": "上市9年每年现金分红全勤，年内多次分红落地，积极落实长期股东回报规划。"
    },
    {
        "code": "600329.SH",
        "name": "达仁堂",
        "industry": "医药生物-中药老字号与机密品种",
        "listing_date": "2001-12-21",
        "continuous_div_years": 24,
        "market_cap": 270.0,
        "float_cap": 270.0,
        "dividend_yield": 10.85,
        "cagr_5y_non_drip": 15.6,
        "cagr_5y_drip": 23.5,
        "is_less_than_5y": False,
        "actual_years_calculated": 5.0,
        "business_scope": "全国大部分在中国",
        "overseas_rev_pct": 2.5,
        "domestic_rev_pct": 97.5,
        "geography_detail": "天津百年中药老字号，速效救心丸等核心产品全国各省市基层医院与零售药店全覆盖，海外为港澳与华人圈出口。",
        "business_model_moat": "速效救心丸为国家机密品种，京万红为秘密品种，拥有近600个药品批准文号，心脑血管急救用药刚需属性极强。",
        "div_policy": "上市24年连续分红全勤，近年来分红率近100%，最新股息率超10%，A股高股息高增长代表标杆。"
    },
    {
        "code": "600548.SH",
        "name": "深高速",
        "industry": "交通运输-大湾区公路与大环保",
        "listing_date": "2001-12-25",
        "continuous_div_years": 24,
        "market_cap": 245.0,
        "float_cap": 175.0,
        "dividend_yield": 5.65,
        "cagr_5y_non_drip": 3.8,
        "cagr_5y_drip": 9.2,
        "is_less_than_5y": False,
        "actual_years_calculated": 5.0,
        "business_scope": "特定区域生意",
        "overseas_rev_pct": 0.0,
        "domestic_rev_pct": 100.0,
        "geography_detail": "核心收费公路资产位于深圳市及广东省粤港澳大湾区核心通道（机荷高速、沿江高速等），100%在中国境内。",
        "business_model_moat": "大湾区核心干道网络特许经营权，深圳先行示范区车流量永续繁荣，拓展固废资源化利用第二主业。",
        "div_policy": "上市24年分红从未间断，分红政策透明连贯，分红率保持在45%-55%区间。"
    },
    {
        "code": "000429.SZ",
        "name": "粤高速A",
        "industry": "交通运输-大湾区核心高速公路",
        "listing_date": "1998-02-20",
        "continuous_div_years": 28,
        "market_cap": 240.0,
        "float_cap": 145.0,
        "dividend_yield": 6.35,
        "cagr_5y_non_drip": 13.2,
        "cagr_5y_drip": 19.5,
        "is_less_than_5y": False,
        "actual_years_calculated": 5.0,
        "business_scope": "特定区域生意",
        "overseas_rev_pct": 0.0,
        "domestic_rev_pct": 100.0,
        "geography_detail": "特许经营核心路桥（广佛高速、佛开高速、京珠高速广珠段）100%位于广东省珠三角腹地，完全依赖区域车流。",
        "business_model_moat": "珠江口东西两岸经济动脉，全国经济最发达、汽车保有量最高的大湾区腹地，资产无衰退风险，折旧后暴利收费。",
        "div_policy": "上市28年连续派现无一年缺席，公告承诺2024-2026年现金分红比例不低于70%，高股息长期复利之王。"
    },
    {
        "code": "000550.SZ",
        "name": "江铃汽车",
        "industry": "汽车-轻型商用车与皮卡SUV",
        "listing_date": "1993-12-01",
        "continuous_div_years": 31,
        "market_cap": 225.0,
        "float_cap": 140.0,
        "dividend_yield": 5.15,
        "cagr_5y_non_drip": 7.5,
        "cagr_5y_drip": 11.8,
        "is_less_than_5y": False,
        "actual_years_calculated": 5.0,
        "business_scope": "全球生意",
        "overseas_rev_pct": 38.5,
        "domestic_rev_pct": 61.5,
        "geography_detail": "国内深耕轻卡、轻客与特种商用车；海外与美国福特深度协同，福特领界、领睿及皮卡大批量出口中东、南美、东盟。",
        "business_model_moat": "福特汽车与江铃深度合资平台，商用车底盘技术积累深厚，海外福特全球销售渠道复用优势极大。",
        "div_policy": "上市31年分红从未间断，数次实施每10股派发数十元的高比例特别派息，分红总额超融资额数百倍。"
    },
    {
        "code": "000581.SZ",
        "name": "威孚高科",
        "industry": "汽车-发动机核心零部件与尾气处理",
        "listing_date": "1998-09-24",
        "continuous_div_years": 26,
        "market_cap": 195.0,
        "float_cap": 165.0,
        "dividend_yield": 5.75,
        "cagr_5y_non_drip": -1.5,
        "cagr_5y_drip": 4.1,
        "is_less_than_5y": False,
        "actual_years_calculated": 5.0,
        "business_scope": "全国大部分在中国",
        "overseas_rev_pct": 12.8,
        "domestic_rev_pct": 87.2,
        "geography_detail": "国内柴油机高压共轨与尾气催化后处理系统配套国内各大主机厂；部分核心精密件出口海外博世集团供应链。",
        "business_model_moat": "与德国博世(Bosch)合资三十年，牢牢把控国内重卡柴油燃油喷射与国六后处理核心供应链，账面净现金充裕。",
        "div_policy": "上市26年未曾中断分红，股利支付率长年维持在50%以上，年年派现。"
    },
    {
        "code": "603444.SH",
        "name": "吉比特",
        "industry": "传媒-精品游戏研发与运营",
        "listing_date": "2017-01-04",
        "continuous_div_years": 8,
        "market_cap": 180.0,
        "float_cap": 180.0,
        "dividend_yield": 6.85,
        "cagr_5y_non_drip": -13.5,
        "cagr_5y_drip": -7.2,
        "is_less_than_5y": False,
        "actual_years_calculated": 5.0,
        "business_scope": "全国大部分在中国",
        "overseas_rev_pct": 16.5,
        "domestic_rev_pct": 83.5,
        "geography_detail": "核心旗舰端手游《问道》《一念逍遥》基本盘在大陆境内；海外设雷霆游戏出海线，在欧美日韩探索轻度放置品类。",
        "business_model_moat": "小步快跑研发机制，长青MMORPG数值模型壁垒深厚，轻资产运营无大额借款与资本开支，ROE极高。",
        "div_policy": "上市8年年年高额分红，上市以来分红总额超60亿元为募资总额的十余倍，分红率常年超80%。"
    },
    {
        "code": "600750.SH",
        "name": "江中药业",
        "industry": "医药生物-OTC胃肠用药与大健康",
        "listing_date": "1996-09-23",
        "continuous_div_years": 28,
        "market_cap": 150.0,
        "float_cap": 150.0,
        "dividend_yield": 5.45,
        "cagr_5y_non_drip": 12.8,
        "cagr_5y_drip": 18.5,
        "is_less_than_5y": False,
        "actual_years_calculated": 5.0,
        "business_scope": "全国大部分在中国",
        "overseas_rev_pct": 0.5,
        "domestic_rev_pct": 99.5,
        "geography_detail": "“江中健胃消食片”“初元”等核心单品深耕国内零售药房毛细渠道，99.5%销售发生在中国境内各省市。",
        "business_model_moat": "华润三九控股赋能，国民级胃肠日常用药心智占领，品牌家喻户晓，轻资产无有息负债，经营净现金流饱满。",
        "div_policy": "上市28年连续派现无一年缺席，近年来现金分红率高达90%至100%，极致派息回馈股东。"
    },
    # --- 3. 细分隐形冠军与区域稳健标杆 (中小市值) ---
    {
        "code": "002233.SZ",
        "name": "塔牌集团",
        "industry": "建筑材料-水泥熟料与建材",
        "listing_date": "2008-05-28",
        "continuous_div_years": 17,
        "market_cap": 98.0,
        "float_cap": 98.0,
        "dividend_yield": 6.85,
        "cagr_5y_non_drip": -1.2,
        "cagr_5y_drip": 5.1,
        "is_less_than_5y": False,
        "actual_years_calculated": 5.0,
        "business_scope": "特定区域生意",
        "overseas_rev_pct": 0.0,
        "domestic_rev_pct": 100.0,
        "geography_detail": "100%位于广东省粤东地区及闽粤赣交界区，水泥销售受制于约200公里经济公路运输半径，纯粹的区域属性。",
        "business_model_moat": "粤东地区石灰石矿山资源垄断，新型干法熟料生产线降本增效，账面持有大量货币现金与结构性存款，零有息负债。",
        "div_policy": "连续17年无间断分红，发布明确三年股东回报规划，分红率高达70%-80%，股息率长年高居建材前茅。"
    },
    {
        "code": "603508.SH",
        "name": "思维列控",
        "industry": "计算机-铁路列控核心安全系统",
        "listing_date": "2015-12-24",
        "continuous_div_years": 10,
        "market_cap": 88.0,
        "float_cap": 88.0,
        "dividend_yield": 5.15,
        "cagr_5y_non_drip": 7.1,
        "cagr_5y_drip": 11.9,
        "is_less_than_5y": False,
        "actual_years_calculated": 5.0,
        "business_scope": "全国大部分在中国",
        "overseas_rev_pct": 0.0,
        "domestic_rev_pct": 100.0,
        "geography_detail": "产品100%服务于中国国家铁路集团（国铁集团）及其下属各铁路局机车机务段，无海外直接收入。",
        "business_model_moat": "列车运行监控记录装置（LKJ）绝对龙头，全国机车与动车装车市占率近50%，安全准入门槛极高，存量设备升级周期确定。",
        "div_policy": "上市10年年年全勤分红，2024年分红率超90%，账面无长短期有息借款，高分红高股息特色突出。"
    },
    {
        "code": "000541.SZ",
        "name": "佛山照明",
        "industry": "家用电器-通用照明与车用LED",
        "listing_date": "1993-11-23",
        "continuous_div_years": 31,
        "market_cap": 82.0,
        "float_cap": 62.0,
        "dividend_yield": 3.85,
        "cagr_5y_non_drip": 1.2,
        "cagr_5y_drip": 4.5,
        "is_less_than_5y": False,
        "actual_years_calculated": 5.0,
        "business_scope": "全球生意",
        "overseas_rev_pct": 32.8,
        "domestic_rev_pct": 67.2,
        "geography_detail": "约33%业务出口欧美日等海外市场，国内深耕民用家居、工程照明及广汽等国内车企车灯配套。",
        "business_model_moat": "“中国灯王”品牌，控股南宁燎旺切入汽车车灯高价值赛道，老牌制造业精细运营与深厚现金储备。",
        "div_policy": "A股历史分红最悠久企业之一，上市31年连续分红从未中断，累计现金分红是募集资金的数十倍。"
    },
    {
        "code": "605016.SH",
        "name": "百龙创园",
        "industry": "基础化工-益生元与阿洛酮糖健康配料",
        "listing_date": "2021-04-21",
        "continuous_div_years": 4,
        "market_cap": 70.0,
        "float_cap": 42.0,
        "dividend_yield": 2.65,
        "cagr_5y_non_drip": 12.1,
        "cagr_5y_drip": 14.8,
        "is_less_than_5y": True,
        "actual_years_calculated": 4.4,
        "business_scope": "全球生意",
        "overseas_rev_pct": 58.5,
        "domestic_rev_pct": 41.5,
        "geography_detail": "海外营收占比近60%，产品通过美国FDA GRAS认证，畅销欧美大健康食品、饮料与代糖巨头客户。",
        "business_model_moat": "全球微生态营养与阿洛酮糖产业化领头羊，合成生物学酶法工艺壁垒高，海外减糖健康趋势直接受益。",
        "div_policy": "上市4年每年全勤分红且持续增长，业绩与分红实现双双健康扩张。"
    },
    {
        "code": "002014.SZ",
        "name": "永新股份",
        "industry": "轻工制造-彩印复合包装材料",
        "listing_date": "2004-07-08",
        "continuous_div_years": 21,
        "market_cap": 66.0,
        "float_cap": 66.0,
        "dividend_yield": 5.65,
        "cagr_5y_non_drip": 7.5,
        "cagr_5y_drip": 13.2,
        "is_less_than_5y": False,
        "actual_years_calculated": 5.0,
        "business_scope": "全国大部分在中国",
        "overseas_rev_pct": 14.8,
        "domestic_rev_pct": 85.2,
        "geography_detail": "国内在黄山、广州、河北等多地建厂就近配套雀巢、伊利、高露洁、宝洁等消费巨头，少量出口东南亚。",
        "business_model_moat": "消费软包装隐形冠军，定制化研发与贴身客户响应壁垒，盈利能力常年优于同行，现金流极其平稳。",
        "div_policy": "上市21年无一年断分红，分红力度持续加码，近五年股利支付率达75%-85%，小而美高股息典范。"
    },
    {
        "code": "605056.SH",
        "name": "咸亨国际",
        "industry": "商贸零售-MRO工业电气集约化服务",
        "listing_date": "2021-07-20",
        "continuous_div_years": 4,
        "market_cap": 49.0,
        "float_cap": 31.0,
        "dividend_yield": 4.85,
        "cagr_5y_non_drip": -2.8,
        "cagr_5y_drip": 1.8,
        "is_less_than_5y": True,
        "actual_years_calculated": 4.2,
        "business_scope": "全国大部分在中国",
        "overseas_rev_pct": 1.5,
        "domestic_rev_pct": 98.5,
        "geography_detail": "98.5%业务深耕国内国家电网、南方电网、中石油及应急管理等大型央国企客户，提供全品类MRO工业品。",
        "business_model_moat": "电网工器具与检测服务集约化供应领头羊，专业技术服务协同，资质准入与央企招投标护城河深厚。",
        "div_policy": "上市以来每年现金分红比例均保持在60%以上，累计分红金额已超IPO募资净额，全勤分红新标杆。"
    },
    {
        "code": "603998.SH",
        "name": "方盛制药",
        "industry": "医药生物-中药创新药与中药配方颗粒",
        "listing_date": "2014-12-05",
        "continuous_div_years": 11,
        "market_cap": 48.0,
        "float_cap": 48.0,
        "dividend_yield": 4.35,
        "cagr_5y_non_drip": 12.2,
        "cagr_5y_drip": 16.5,
        "is_less_than_5y": False,
        "actual_years_calculated": 5.0,
        "business_scope": "全国大部分在中国",
        "overseas_rev_pct": 0.0,
        "domestic_rev_pct": 100.0,
        "geography_detail": "中药制剂产品100%在国内各级医疗机构与零售药店终端销售，主打骨伤科与心脑血管用药。",
        "business_model_moat": "创新中药“藤黄健骨片”“玄七健骨片”双轮驱动，聚焦主业剥离非核心资产，现金流充裕。",
        "div_policy": "连续11年分红未曾间断，创新推出“一年三次分红”（年度+中期+特别分红），持续提升股东获得感。"
    },
    {
        "code": "603165.SH",
        "name": "荣晟环保",
        "industry": "轻工制造-牛皮箱板纸与再生包装",
        "listing_date": "2017-01-17",
        "continuous_div_years": 8,
        "market_cap": 39.0,
        "float_cap": 39.0,
        "dividend_yield": 10.25,
        "cagr_5y_non_drip": 4.8,
        "cagr_5y_drip": 13.8,
        "is_less_than_5y": False,
        "actual_years_calculated": 5.0,
        "business_scope": "特定区域生意",
        "overseas_rev_pct": 0.0,
        "domestic_rev_pct": 100.0,
        "geography_detail": "基地位于浙江嘉兴平湖，100%业务服务于长三角核心经济圈包装瓦楞纸箱客户，具有约200公里经济辐射圈限制。",
        "business_model_moat": "热电联产、废纸制浆造纸一体化循环经济壁垒，环保排污指标刚性约束，区域环保准入护城河坚固。",
        "div_policy": "上市8年年年分红，2024-2025年一年实施3次分红，分红总额超当年净利润两倍，股息率超10%。"
    },
    {
        "code": "002763.SZ",
        "name": "汇洁股份",
        "industry": "纺织服饰-品牌内衣与贴身衣物",
        "listing_date": "2015-06-10",
        "continuous_div_years": 10,
        "market_cap": 33.0,
        "float_cap": 33.0,
        "dividend_yield": 11.25,
        "cagr_5y_non_drip": 3.2,
        "cagr_5y_drip": 12.1,
        "is_less_than_5y": False,
        "actual_years_calculated": 5.0,
        "business_scope": "全国大部分在中国",
        "overseas_rev_pct": 2.1,
        "domestic_rev_pct": 97.9,
        "geography_detail": "国内直营+加盟门店逾千家，覆盖全国一二三线商场专柜，线上天猫京东唯品会全渠道，绝大部分销售在境内。",
        "business_model_moat": "旗下“曼妮芬”“伊维斯”中国驰名商标，研发版型数据库深厚，品牌溢价与女性贴身内衣高复购属性，净现金充沛。",
        "div_policy": "上市10年无一断档，全年每10股派现超8元，分红总额超当年净利润，最新股息率高达11.69%。"
    },
    {
        "code": "301020.SZ",
        "name": "密封科技",
        "industry": "汽车-发动机密封垫片及新能源密封",
        "listing_date": "2021-07-06",
        "continuous_div_years": 4,
        "market_cap": 29.0,
        "float_cap": 18.0,
        "dividend_yield": 4.10,
        "cagr_5y_non_drip": -0.5,
        "cagr_5y_drip": 3.9,
        "is_less_than_5y": True,
        "actual_years_calculated": 4.2,
        "business_scope": "全国大部分在中国",
        "overseas_rev_pct": 11.5,
        "domestic_rev_pct": 88.5,
        "geography_detail": "国内主要配套潍柴动力、一汽解放、中国重汽等头部内燃机厂，部分密封产品出口海外商用车后市场。",
        "business_model_moat": "内燃机发动机密封行业专精特新“小巨人”，技术打破国外垄断，氢燃料电池气气密封及储能密封打开新空间。",
        "div_policy": "上市4年全勤分红，明确章程在满足条件时每年现金分红比例不低于可分配利润的60%。"
    }
]

print(f"Total curated companies meeting strict continuous dividend criteria: {len(DATA)}")
